# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_c.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ANC_interface(object):
    def setupUi(self, ANC_interface):
        ANC_interface.setObjectName("ANC_interface")
        ANC_interface.resize(1021, 714)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("UI/icons/nsicon-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ANC_interface.setWindowIcon(icon)
        ANC_interface.setStyleSheet("background-color: rgb(50, 50, 50);\n"
"font: 8pt \"Arial\";\n"
"font: 8pt \"Comic Sans MS\";")
        self.centralwidget = QtWidgets.QWidget(ANC_interface)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("/* Tab Widget Background */\n"
"QTabWidget::pane {\n"
"    background: #1e272e; /* Dark background for tab content */\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* Tab Bar */\n"
"QTabBar::tab {\n"
"    background: #aaa; /* Dark gray tab background */\n"
"    color: #aaa; /* Light text color */\n"
"    border: 1px solid #555; /* Darker border */\n"
"    padding: -5px 5px 10px 5px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"/* Selected (Active) Tab */\n"
"QTabBar::tab:selected {\n"
"  background: #f1f1ff ;\n"
"    /*background: qlineargradient(spread:pad, x1:0.339, y1:0.767045, x2:1, y2:0, stop:0 rgba(255, 255, 127, 255), stop:1 rgba(255, 255, 255, 255)); /* Blue for active tab */\n"
"    color: #999;\n"
"   /* border: 2px solid #fafa98;*/\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* Hover Effect */\n"
"QTabBar::tab:hover {\n"
"    background: #fff; /* Lighter blue when hovering */\n"
"/*background: qlineargradient(spread:pad, x1:0.339, y1:0.767045, x2:1, y2:0, stop:0 rgba(255, 255, 127, 255), stop:1 rgba(255, 255, 255, 255)); /* Blue for active tab */\n"
"    /*border: 1px solid black;*/\n"
"}\n"
"\n"
"/* Inactive Tabs */\n"
"QTabBar::tab:!selected {\n"
"background: rgb(208, 221, 204); /* Dark gray */\n"
"/*    background: qlineargradient(spread:pad, x1:0.339, y1:0.767045, x2:1, y2:0, stop:0 rgba(80, 100, 80, 255), stop:1 rgba(255, 255, 255, 255)); /* Blue for active tab */\n"
"    color: #bdc3c7; /* Light gray text */\n"
"}\n"
"\n"
"/* Disabled Tabs */\n"
"QTabBar::tab:disabled {\n"
"    color: #7f8c8d; /* Faded text */\n"
"    background: #3a4f5c;\n"
"    border-color: #2c3e50;\n"
"}\n"
"QTabWidget::tab-bar {\n"
"    alignment: left; /* Aligns the tab bar to the center */\n"
"}\n"
"\n"
"/*Group boxes*/\n"
"/* GroupBox Main Styling */\n"
"QGroupBox {\n"
"    border: 2px solid #777; /*rgb(255, 255, 127);*/ /* Slightly lighter border */\n"
"    border-radius: 8px;\n"
"    margin-top: 30px; /* Space for title */\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"/* GroupBox Title */\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left; /* Center the title */\n"
"    background-color: transparent; /* No background for title */\n"
"    padding: 5px 10px;\n"
"    color: rgb(214, 211, 230) /*rgb(255, 255, 127); /* Blue title color */\n"
"}\n"
"\n"
"/* GroupBox When Disabled */\n"
"QGroupBox:disabled {\n"
"    color: #7f8c8d; /* Faded text color */\n"
"    border-color: #3a4f5c;\n"
"}\n"
"\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setIconSize(QtCore.QSize(20, 30))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("/* Default Button */\n"
"QPushButton {\n"
"    background-color: rgb(191, 200, 187);\n"
"    color: #555; /* */\n"
"    border:None;\n"
"  /*  border-bottom: 3px solid rgb(160, 160, 0); \n"
"    border-right: 3px solid rgb(160, 160, 0);*/\n"
"    border-radius: 5px;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"/* Hover Effect */\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 0, 175);  /* Slightly lighter on hover */\n"
"    border: None;  /* Blue border */\n"
"    color: white;\n"
"}\n"
"\n"
"/* Pressed Effect */\n"
"QPushButton:pressed {\n"
"    background-color: #1f2e3d;  /* Darker shade when pressed */\n"
"    border: 2px solid #2980b9;  /* Darker blue border */\n"
"}\n"
"\n"
"/* Disabled Button */\n"
"QPushButton:disabled {\n"
"    background-color: #3a4f5c;  /* Muted gray */\n"
"    color: #7f8c8d;  /* Faded text */\n"
"    border: 2px solid #2c3e50;\n"
"}\n"
"")
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.tab)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 130))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_9 = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setStyleSheet("")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_4.setSpacing(4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Show_residual_btn = QtWidgets.QPushButton(self.frame_9)
        self.Show_residual_btn.setMinimumSize(QtCore.QSize(0, 39))
        self.Show_residual_btn.setObjectName("Show_residual_btn")
        self.horizontalLayout_4.addWidget(self.Show_residual_btn)
        self.show_ps_btn = QtWidgets.QPushButton(self.frame_9)
        self.show_ps_btn.setMinimumSize(QtCore.QSize(0, 39))
        self.show_ps_btn.setObjectName("show_ps_btn")
        self.horizontalLayout_4.addWidget(self.show_ps_btn)
        self.start_recording_btn = QtWidgets.QPushButton(self.frame_9)
        self.start_recording_btn.setMinimumSize(QtCore.QSize(0, 39))
        self.start_recording_btn.setObjectName("start_recording_btn")
        self.horizontalLayout_4.addWidget(self.start_recording_btn)
        self.clean_the_audio_btn = QtWidgets.QPushButton(self.frame_9)
        self.clean_the_audio_btn.setMinimumSize(QtCore.QSize(0, 39))
        self.clean_the_audio_btn.setObjectName("clean_the_audio_btn")
        self.horizontalLayout_4.addWidget(self.clean_the_audio_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_5.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_3.setContentsMargins(5, 2, 5, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.restart_btn = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restart_btn.sizePolicy().hasHeightForWidth())
        self.restart_btn.setSizePolicy(sizePolicy)
        self.restart_btn.setMinimumSize(QtCore.QSize(0, 39))
        self.restart_btn.setStyleSheet("padding:0px 10px ;\n"
"background-color: rgba(64, 127, 191, 255); /* qlineargradient(spread:pad, x1:0.339, y1:0.767045, x2:1, y2:0, stop:0 rgba(64, 127, 191, 255), stop:1 rgba(255, 255, 255, 255));*/")
        self.restart_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("UI/icons/backward-track.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restart_btn.setIcon(icon1)
        self.restart_btn.setIconSize(QtCore.QSize(16, 16))
        self.restart_btn.setObjectName("restart_btn")
        self.horizontalLayout_3.addWidget(self.restart_btn)
        self.Play_pause_btn = QtWidgets.QPushButton(self.frame_10)
        self.Play_pause_btn.setMinimumSize(QtCore.QSize(42, 39))
        self.Play_pause_btn.setStyleSheet("padding:0px 5px;\n"
"background-color: rgb(64, 127, 191);\n"
"/*background-color: qlineargradient(spread:pad, x1:0.339, y1:0.767045, x2:1, y2:0, stop:0 rgba(64, 127, 191, 255), stop:1 rgba(255, 255, 255, 255));*/")
        self.Play_pause_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("UI/icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Play_pause_btn.setIcon(icon2)
        self.Play_pause_btn.setIconSize(QtCore.QSize(20, 20))
        self.Play_pause_btn.setObjectName("Play_pause_btn")
        self.horizontalLayout_3.addWidget(self.Play_pause_btn)
        self.line = QtWidgets.QFrame(self.frame_10)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_3.addWidget(self.line)
        self.add_Audio_btn = QtWidgets.QPushButton(self.frame_10)
        self.add_Audio_btn.setMinimumSize(QtCore.QSize(0, 39))
        self.add_Audio_btn.setObjectName("add_Audio_btn")
        self.horizontalLayout_3.addWidget(self.add_Audio_btn)
        self.browse_noise_audio_btn = QtWidgets.QPushButton(self.frame_10)
        self.browse_noise_audio_btn.setMinimumSize(QtCore.QSize(0, 39))
        self.browse_noise_audio_btn.setObjectName("browse_noise_audio_btn")
        self.horizontalLayout_3.addWidget(self.browse_noise_audio_btn)
        self.noise_type_comboBox = QtWidgets.QComboBox(self.frame_10)
        self.noise_type_comboBox.setMinimumSize(QtCore.QSize(0, 39))
        self.noise_type_comboBox.setStyleSheet("/* ComboBox Main Styling */\n"
"QComboBox {\n"
"    background-color: #2c3e50; /* Dark background */\n"
"    border: 2px solid #34495e; /* Slightly lighter border */\n"
"    border-radius: 6px;\n"
"    padding: 5px 10px;\n"
"    color: #ecf0f1; /* Light text */\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Dropdown Arrow */\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 20px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(down-arrow.png); /* Replace with actual path if needed */\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:hover {\n"
"    image: url(down-arrow-hover.png);\n"
"}\n"
"\n"
"/* Popup List */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #2c3e50; /* Dark background */\n"
"    border: 1px solid #34495e;\n"
"    selection-background-color: #2980b9; /* Blue highlight for selection */\n"
"    selection-color: white;\n"
"    padding: 4px;\n"
"}\n"
"\n"
"/* Hover Effect */\n"
"QComboBox:hover {\n"
"    background-color: #3b5366;\n"
"    border: 2px solid #5dade2; /* Blue border */\n"
"}\n"
"\n"
"/* When Pressed */\n"
"QComboBox:pressed, QComboBox:on {\n"
"    background-color: #1f2e3d;\n"
"    border: 2px solid #2980b9;\n"
"}\n"
"\n"
"/* Disabled */\n"
"QComboBox:disabled {\n"
"    background-color: #3a4f5c;\n"
"    color: #7f8c8d;\n"
"    border-color: #2c3e50;\n"
"}\n"
"")
        self.noise_type_comboBox.setFrame(True)
        self.noise_type_comboBox.setObjectName("noise_type_comboBox")
        self.horizontalLayout_3.addWidget(self.noise_type_comboBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_5.addWidget(self.frame_10)
        self.frame_2 = QtWidgets.QFrame(self.splitter)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.frame_2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(230, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setContentsMargins(5, 7, 5, 5)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget.sizePolicy().hasHeightForWidth())
        self.treeWidget.setSizePolicy(sizePolicy)
        self.treeWidget.setMaximumSize(QtCore.QSize(220, 16777215))
        self.treeWidget.setStyleSheet("/* QTreeWidget Background and Borders */\n"
"QTreeWidget {\n"
"    background-color: #2c3e50; /* Dark background */\n"
"    border: 1px solid #1e272e; /* Darker border */\n"
"    color: #ecf0f1; /* Light text */\n"
"    font-size: 14px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"/* Alternate Row Colors */\n"
"QTreeWidget::item {\n"
"    background-color: #34495e; /* Default row background */\n"
"}\n"
"\n"
"QTreeWidget::item:alternate {\n"
"    background-color: #3b5366; /* Slightly lighter background for alternate rows */\n"
"}\n"
"\n"
"/* Selected Item */\n"
"QTreeWidget::item:selected {\n"
"    background-color: #2980b9; /* Blue selection */\n"
"    color: white;\n"
"    border: 1px solid #1f618d;\n"
"}\n"
"\n"
"/* Hover Effect */\n"
"QTreeWidget::item:hover {\n"
"    background-color: #5dade2; /* Light blue on hover */\n"
"}\n"
"\n"
"/* Disabled Items */\n"
"QTreeWidget::item:disabled {\n"
"    color: #7f8c8d; /* Muted text */\n"
"    background-color: #3a4f5c;\n"
"}\n"
"\n"
"/* Scrollbar Styling */\n"
"QTreeWidget QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #2c3e50;\n"
"    width: 10px;\n"
"}\n"
"\n"
"QTreeWidget QScrollBar::handle:vertical {\n"
"    background: #3498db;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTreeWidget QScrollBar::handle:vertical:hover {\n"
"    background: #2980b9;\n"
"}\n"
"\n"
"QTreeWidget QScrollBar::add-line, \n"
"QTreeWidget QScrollBar::sub-line {\n"
"    background: none;\n"
"    border: none;\n"
"}\n"
"")
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.header().setVisible(False)
        self.treeWidget.header().setDefaultSectionSize(50)
        self.treeWidget.header().setMinimumSectionSize(10)
        self.treeWidget.header().setSortIndicatorShown(False)
        self.treeWidget.header().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.treeWidget)
        self.groupBox_4 = QtWidgets.QGroupBox(self.splitter_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.spectrumViewbox = QtWidgets.QTableWidget(self.groupBox_4)
        self.spectrumViewbox.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.spectrumViewbox.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.spectrumViewbox.setObjectName("spectrumViewbox")
        self.spectrumViewbox.setColumnCount(2)
        self.spectrumViewbox.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.spectrumViewbox.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.spectrumViewbox.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.spectrumViewbox.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.spectrumViewbox.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.spectrumViewbox.setItem(0, 1, item)
        self.spectrumViewbox.horizontalHeader().setVisible(False)
        self.spectrumViewbox.horizontalHeader().setDefaultSectionSize(52)
        self.spectrumViewbox.horizontalHeader().setStretchLastSection(True)
        self.spectrumViewbox.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout_7.addWidget(self.spectrumViewbox)
        self.horizontalLayout.addWidget(self.splitter_2)
        self.verticalLayout_2.addWidget(self.splitter)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("UI/icons/analysis_9828989.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("UI/icons/analysis_9828873.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap("UI/icons/analysis_9828989.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_7 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.splitter_3 = QtWidgets.QSplitter(self.frame_7)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.groupBox_11 = QtWidgets.QGroupBox(self.splitter_3)
        self.groupBox_11.setObjectName("groupBox_11")
        self.groupBox_12 = QtWidgets.QGroupBox(self.splitter_3)
        self.groupBox_12.setObjectName("groupBox_12")
        self.groupBox_13 = QtWidgets.QGroupBox(self.splitter_3)
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_6.addWidget(self.splitter_3)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.groupBox_5)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_3.addWidget(self.frame_8)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("UI/icons/sharing_954869.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap("UI/icons/sharing_955097.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_2, icon4, "")
        self.verticalLayout.addWidget(self.tabWidget)
        ANC_interface.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ANC_interface)
        self.statusbar.setObjectName("statusbar")
        ANC_interface.setStatusBar(self.statusbar)
        self.actionNew_project = QtWidgets.QAction(ANC_interface)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionOpen_recent = QtWidgets.QAction(ANC_interface)
        self.actionOpen_recent.setObjectName("actionOpen_recent")
        self.actionOpen_old_project = QtWidgets.QAction(ANC_interface)
        self.actionOpen_old_project.setObjectName("actionOpen_old_project")

        self.retranslateUi(ANC_interface)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ANC_interface)

    def retranslateUi(self, ANC_interface):
        _translate = QtCore.QCoreApplication.translate
        ANC_interface.setWindowTitle(_translate("ANC_interface", "NoiseShield"))
        self.tabWidget.setToolTip(_translate("ANC_interface", "<html><head/><body><p>ANC Experiment</p></body></html>"))
        self.groupBox.setTitle(_translate("ANC_interface", "Settings"))
        self.Show_residual_btn.setText(_translate("ANC_interface", "Show residual"))
        self.show_ps_btn.setText(_translate("ANC_interface", "Show power spectrum"))
        self.start_recording_btn.setText(_translate("ANC_interface", "Start recording"))
        self.clean_the_audio_btn.setText(_translate("ANC_interface", "Denoise"))
        self.restart_btn.setShortcut(_translate("ANC_interface", "Ctrl+R"))
        self.Play_pause_btn.setShortcut(_translate("ANC_interface", "Ctrl+P"))
        self.add_Audio_btn.setText(_translate("ANC_interface", "Import Audio file"))
        self.browse_noise_audio_btn.setText(_translate("ANC_interface", "Browse for Noise audio"))
        self.noise_type_comboBox.setPlaceholderText(_translate("ANC_interface", "Select a noise signal"))
        self.groupBox_3.setTitle(_translate("ANC_interface", "Signal Index Tree"))
        self.treeWidget.headerItem().setText(0, _translate("ANC_interface", "Audio Items"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("ANC_interface", "⏹️     Signal 1"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("ANC_interface", "⏹️     Signal 2"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_4.setTitle(_translate("ANC_interface", "Signal waveform viewbox"))
        item = self.spectrumViewbox.verticalHeaderItem(0)
        item.setText(_translate("ANC_interface", "1"))
        item = self.spectrumViewbox.horizontalHeaderItem(0)
        item.setText(_translate("ANC_interface", "signal profile index"))
        item = self.spectrumViewbox.horizontalHeaderItem(1)
        item.setText(_translate("ANC_interface", "Waveform"))
        __sortingEnabled = self.spectrumViewbox.isSortingEnabled()
        self.spectrumViewbox.setSortingEnabled(False)
        item = self.spectrumViewbox.item(0, 0)
        item.setText(_translate("ANC_interface", "1"))
        item = self.spectrumViewbox.item(0, 1)
        item.setText(_translate("ANC_interface", "jnjjkj"))
        self.spectrumViewbox.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab), _translate("ANC_interface", "ANC experiment"))
        self.groupBox_5.setTitle(_translate("ANC_interface", "This side"))
        self.groupBox_11.setTitle(_translate("ANC_interface", "Recorded signal waveform"))
        self.groupBox_12.setTitle(_translate("ANC_interface", "Noise signal waveform"))
        self.groupBox_13.setTitle(_translate("ANC_interface", "Transmitted signal waveform"))
        self.groupBox_6.setTitle(_translate("ANC_interface", "Receiver end"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_2), _translate("ANC_interface", "Real time communication"))
        self.actionNew_project.setText(_translate("ANC_interface", "New project"))
        self.actionOpen_recent.setText(_translate("ANC_interface", "Open  recent"))
        self.actionOpen_old_project.setText(_translate("ANC_interface", "Open old project"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ANC_interface = QtWidgets.QMainWindow()
    ui = Ui_ANC_interface()
    ui.setupUi(ANC_interface)
    ANC_interface.show()
    sys.exit(app.exec_())
